@extends('layout-landing.master')

@section('title')
    <title>Kontakami - Syarat & Ketentuan</title>
@endsection()
@section('seo')
    <meta name="description" content="Syarat & Ketentuan">
    <link rel="canonical" href="https://kontakami.com/terms-condition" />
@endsection()

@section('content')
    <div class="relative bg-cover bg-center h-96" style="background-image: url('/img/rebranding/syarat-ketentuan-banner.webp');">
        <div class="relative max-w-7xl mx-auto h-full flex items-center justify-center text-center px-4 md:px-8">
            <div class="text-white">
                <h1 class="text-4xl md:text-6xl font-bold mb-6 font-montserrat">Syarat & Ketentuan</h1>
                <ul class="decoration-none flex flex-row gap-2 justify-center font-ubuntu">
                    <li><a href="/" class="hover:text-slate-200">Home</a></li>
                    <li>
                        <p>></p>
                    </li>
                    <li><a href="/faq" class="hover:text-slate-200">Support</a></li>
                    <li>
                        <p>></p>
                    </li>
                    <li><a href="/terms-condition" class="hover:text-slate-200">Syarat & Ketentuan</a></li>
                </ul>
            </div>
        </div>
                <div class="py-2 bg-orange">
        </div>
    </div>

    <div class="flex flex-col items-center justify-center">
        <div class="py-16 mx-10 max-w-7xl font-ubuntu">
            <div class="text-left overflow-hidden">
                <p class="mb-4">Syarat-syarat dan ketentuan-ketentuan penggunaan ini <span class="font-bold">("Ketentuan Penggunaan")</span> mengatur hubungan antara "<span class="font-bold">PT APLIKASI YELLOW OLAHKATA ("KONTAKAMI", "kami", atau "milik kami")</span> dengan penggunanya <span class="font-bold">("Pengguna", "Anda")</span> sehubungan dengan Layanan (sebagaimana didefinisikan di bawah ini).</p>
            <p class="mb-4">KONTAKAMI menyediakan layanan-layanan sebagaimana berikut:</p>
            <ol class="list-decimal pl-6 mb-4">
                <li>Aplikasi KONTAKAMI beserta situs www.kontakami.com</li>
                <li>Konten pencarian alamat kontak bisnis jasa maupun pencarian lainnya</li>
                <li>Inbound dan outbound melalui panggilan suara dan chat</li>
                <li>Konten pembelian ataupun jasa melalui aplikasi yang terhubung dengan Business Account (merupakan pihak yang menampilkan iklan barang ataupun jasa di aplikasi KONTAKAMI)</li>
                <li>Layanan, konten, update, fitur, perangkat lunak dan produk lainnya serta rilis baru yang mungkin kami sediakan dari waktu ke waktu, (selanjutnya secara bersama-sama disebut sebagai "<span class="font-bold">Layanan</span>").</li>
            </ol>
            <p class="mb-4">Layanan ini disediakan oleh KONTAKAMI melalui aplikasi yang Anda unduh ke perangkat Anda atau ke perangkat yang disediakan oleh KONTAKAMI ("<span class="font-bold">Aplikasi</span>"). Harap baca dengan seksama syarat dan ketentuan berikut ("<span class="font-bold">Ketentuan Layanan</span>") dan Kebijakan Privasi kami, dan yang dimasukkan di sini dengan merujuk ke Ketentuan Layanan ini.</p>
            <p class="mb-4">Bahwa Layanan KONTAKAMI yang terhubung dengan Pihak lainnya, termasuk namun tidak terbatas pada layanan pembayaran maupun layanan mitra KONTAKAMI, akan mengikuti syarat dan ketentuan yang diatur tersendiri oleh pemilik layanan tersebut ("<span class="font-bold">Ketentuan Layanan Pihak Ketiga</span>"), KONTAKAMI tidak bertanggungjawab atas segala permasalahan yang timbul dari layanan dimaksud.</p>
            <p class="mb-4">Ketentuan Layanan ini mengatur akses Anda ke dan penggunaan Layanan KONTAKAMI dan semua Konten Situs dan merupakan perjanjian hukum yang mengikat antara Anda dan KONTAKAMI ("<span class="font-bold">Perjanjian</span>").</p>
            <p class="mb-4">Anda mengakui dan sepakat bahwa, dari waktu ke waktu, KONTAKAMI dapat menambah, mengubah atau menghilangkan seluruh atau sebagian fitur atau fungsi dalam Layanan. Pengguna dapat melakukan instalasi atas versi terbaru untuk menerima perubahan-perubahan tersebut. KONTAKAMI juga dapat memutuskan untuk berhenti menyediakan seluruh atau sebagian dari Layanan pada setiap waktu, dan tidak ada satu ketentuan pun di dalam Ketentuan Penggunaan ini yang dapat dijadikan sebagai jaminan bahwa Aplikasi atau bagian dari Layanan manapun akan selalu tersedia, baik pada bentuk saat ini atau bentuk lainnya, dan/atau bahwa KONTAKAMI akan terus mendukung, menjaga, atau meneruskan untuk menawarkan Layanan dan/atau Aplikasi atau versi manapun daripadanya.</p>
            <p class="font-bold mb-4">ANDA MENGAKUI DAN MENYETUJUI BAHWA, DENGAN MENGKLIK TOMBOL "MENERIMA PERSYARATAN", MENDAFTAR UNTUK REGISTRASI KONTAKAMI, MENGUNDUH APLIKASI KONTAKAMI ATAU LAYANAN, MENGGUNAKAN APLIKASI PADA PERANGKAT ANDA, PERANGKAT YANG DISEDIAKAN, ATAU MENGGUNAKAN LAYANAN DARI KONTAKAMI, ANDA MENUNJUKKAN BAHWA ANDA TELAH MEMBACA, MEMAHAMI, DAN SETUJU UNTUK TERIKAT DENGAN KETENTUAN LAYANAN INI. JIKA ANDA TIDAK MENYETUJUI KETENTUAN LAYANAN INI, ANDA TIDAK BERHAK MEMILIKI AKSES ATAU MENGGUNAKAN LAYANAN.</p>
            <p class="mb-4">Jika Anda menerima atau menyetujui Ketentuan Layanan ini atas nama perusahaan atau badan hukum lain, Anda menyatakan dan menjamin bahwa Anda memiliki wewenang untuk mengikat perusahaan atau badan hukum lain yang bersangkutan dengan Ketentuan Layanan ini dan, dalam hal demikian, "Anda" akan mengacu dan berlaku pada perusahaan atau badan hukum lainnya.</p>
            <p class="mb-4">Anda mengakui dan sepakat bahwa, KONTAKAMI dapat menawarkan fitur khusus dan/atau promosi yang memiliki syarat-syarat dan ketentuan-ketentuan tersendiri disamping Ketentuan Penggunaan ini ("<span class="font-bold">Ketentuan Khusus</span>"). Dalam hal tersebut, Ketentuan Khusus tersebut akan mengatur ketidaksesuaian dengan bagian tertentu dalam Ketentuan Penggunaan ini.</p>

            <p class="font-bold mb-4 underline">Menerima Ketentuan</p>
            <p class="mb-4">Dengan menggunakan informasi, alat, fitur, perangkat lunak, dan fungsionalitas termasuk konten, pembaruan, dan rilis baru yang disediakan oleh KONTAKAMI, Anda setuju untuk terikat oleh Perjanjian ini, apakah Anda seorang "Pengunjung" (yang berarti bahwa Anda cukup menelusuri aplikasi mobile KONTAKAMI dan situs web KONTAKAMI (administrasi)), "KONTAKAMI" (yang berarti Anda telah terdaftar di KONTAKAMI). Istilah "Anda" atau "Pengguna" mengacu pada Pengunjung, Pengguna. Istilah "Kami" mengacu pada KONTAKAMI.</p>
            <p class="mb-4">Jika Anda ingin menggunakan Layanan, Anda harus membaca Perjanjian ini dan menunjukkan penerimaan Anda selama proses pendaftaran. Anda tidak boleh menggunakan Layanan KONTAKAMI dan Anda tidak dapat menerima Perjanjian ini jika Anda belum berusia paling tidak 18 tahun, dalam keadaan apa pun, dari usia yang sah untuk membentuk kontrak yang mengikat dengan KONTAKAMI.</p>
            <p class="mb-4">Jika Anda menerima Perjanjian ini, Anda menyatakan bahwa Anda memiliki kapasitas untuk terikat olehnya atau jika Anda bertindak atas nama perusahaan atau entitas yang Anda memiliki wewenang untuk mengikat entitas tersebut.</p>

            <p class="font-bold mb-4 underline">Privasi dan Informasi Pribadi Anda</p>
            <p class="mb-4">Anda menyetujui Pernyataan Privasi KONTAKAMI yang berlaku, dan segala perubahan yang dipublikasikan oleh KONTAKAMI. Anda setuju bahwa KONTAKAMI dapat menggunakan dan mengelola data Anda sesuai dengan Pernyataan Privasi KONTAKAMI, sebagai bagian dari Layanan. Anda memberikan izin kepada KONTAKAMI untuk menggabungkan informasi yang Anda masukkan atau unggah untuk Layanan dengan pengguna Layanan lainnya dan/atau layanan KONTAKAMI lainnya.</p>

            <p class="font-bold mb-4 underline">Deskripsi Layanan</p>
            <p class="mb-4">Anda mengakui dan sepakat bahwa Layanan terdiri dari Layanan yang disediakan secara gratis ("<span class="font-bold">Basic Service</span>") dan berdasarkan pembayaran. Basic Service hanya memberikan akses kepada Anda untuk Layanan dan fitur tertentu yang bersifat terbatas. Layanan dan fitur lainnya hanya dapat diakses oleh Anda setelah pembayaran ("<span class="font-bold">Pay Per Use</span>").</p>
            <p class="mb-4">Seluruh data yang Anda simpan sehubungan dengan Layanan akan tersimpan dan dapat diakses kembali ketika Anda masuk ke dalam layanan aplikasi mobile KONTAKAMI. Anda mengakui dan sepakat bahwa KONTAKAMI berhak menghapus data Anda apabila tidak terdapat aktivitas selama 30 (tiga puluh) hari dari terakhir kali akun Anda aktif di aplikasi mobile KONTAKAMI atau batas waktu lain yang ditetapkan oleh peraturan yang berlaku dari KONTAKAMI.</p>
            <p class="mb-4">Layanan dapat mencakup fitur yang menghubungkan Anda ke salah satu mitra kami. Apabila Anda memilih menggunakan Layanan ini, Anda memahami dan sepakat untuk tunduk dan terikat pada syarat dan ketentuan yang berlaku dari mitra, yang melengkapi Ketentuan Penggunaan ini.</p>
            <p class="mb-4">Layanan juga dapat memberikan informasi yang berkaitan dengan produk atau layanan pihak ketiga ("<span class="font-bold">Penawaran</span>"), serta memberikan Anda tips umum, rekomendasi, dan materi-materi.</p>

            <p class="font-bold mb-4 underline">Pembayaran</p>
            <p class="mb-4">Pengguna mengakui bahwa dengan membeli Layanan, Pengguna sepakat terhadap biaya atau harga yang terkait sebagaimana (i) tertera pada Aplikasi dan/atau Situs pada saat pembelian Layanan, dan (ii) diubah dari waktu ke waktu sesuai dengan Ketentuan Penggunaan ini.</p>
            <p class="mb-4">Anda mengakui dan sepakat bahwa KONTAKAMI dapat sewaktu-waktu, atas kebijaksanaannya sendiri, mengubah ketentuan pembebanan biaya dan harga yang berlaku terhadap jenis Layanan apapun, termasuk mengubah biaya dan harga Layanan, dengan memberikan pemberitahuan kepada Anda.</p>
            <p class="mb-4">Jika pembayaran Anda di akhir proses pendaftaran Anda tidak lengkap, tidak terkirim, atau tidak lengkap, kemudian Anda tidak memberitahukan KONTAKAMI secepatnya setelah terjadinya perubahan informasi, Anda mengakui dan sepakat bahwa KONTAKAMI dapat menolak menyediakan Anda penggunaan Pay Per Use dalam bentuk apapun.</p>
            <p class="mb-4">Apabila Pengguna menghendaki pengembalian dana, Anda mengakui dan sepakat bahwa klaim akan menerima pengembalian atas setiap pembayaran yang telah dilakukan, kecuali atas kesepakatan tersendiri dengan Business Account yang dipilih, dimana KONTAKAMI tidak bertanggungjawab atas pengembalian apapun.</p>
            <p class="mb-4">Anda mengakui dan sepakat bahwa Pajak yang timbul sehubungan dengan Layanan ini akan menjadi beban dan tanggung jawab masing-masing Pihak sesuai dengan ketentuan dan peraturan perundang-undangan mengenai perpajakan yang berlaku.</p>

            <p class="font-bold mb-4 underline">Informasi Pendaftaran Anda</p>
            <p class="mb-4">Untuk memungkinkan Anda menggunakan Layanan, Anda harus mendaftar untuk akun di KONTAKAMI. Kami dapat memverifikasi identitas Anda. Anda memberi wewenang kepada kami untuk mengajukan pertanyaan yang kami anggap perlu untuk memverifikasi identitas Anda. Pertanyaan-pertanyaan ini mungkin termasuk meminta Anda untuk informasi lebih lanjut, mengharuskan Anda untuk memberikan alamat lengkap dan/atau menghubungkan Anda untuk mengambil langkah-langkah untuk mengkonfirmasi kepemilikan alamat email atau instrumen keuangan Anda, atau memverifikasi informasi lainnya yang Anda berikan kepada pihak ketiga atau melalui sumber lain. Jika Anda tidak memberikan informasi ini, KONTAKAMI tidak dapat memverifikasi identitas Anda, kami dapat menolak untuk mengizinkan Anda menggunakan Layanan.</p>
            <p class="mb-4">Anda setuju dan memahami bahwa Anda bertanggung jawab untuk menjaga kerahasiaan kata sandi Anda, yang bersamaan dengan alamat email Login ID Anda, memungkinkan Anda untuk mengakses Layanan. Login ID dan password, bersama dengan nomor ponsel atau informasi lain yang Anda berikan membentuk "Informasi Pendaftaran." Dengan memberikan alamat e-mail, Anda setuju untuk menerima semua pemberitahuan yang diperlukan secara elektronik, melalui Layanan dengan menampilkan link ke pemberitahuan umum di Layanan, ke alamat email tersebut. Adalah tanggung jawab Anda untuk memperbarui atau menggubah alamat email tersebut, jika perlu.</p>
            <p class="mb-4">Jika Anda mengetahui adanya penggunaan yang tidak sah atas Pendaftaran atau Informasi Akun Anda untuk Layanan, Anda setuju untuk segera memberi tahu KONTAKAMI. Jika Anda yakin bahwa Pendaftaran atau Informasi Akun atau perangkat yang Anda gunakan untuk mengakses KONTAKAMI telah hilang atau dicuri, bahwa seseorang menggunakan akun Anda tanpa izin Anda, Anda harus memberitahu KONTAKAMI segera dalam rangka untuk meminimalkan kerugian yang mungkin Anda.</p>

            <p class="font-bold mb-4 underline">Penggunaan Layanan oleh Anda</p>
            <p class="mb-4">Hak Anda untuk mengakses dan menggunakan Layanan bersifat pribadi untuk Anda dan tidak dapat dialihkan oleh Anda kepada orang atau entitas lain mana pun. Anda hanya berhak untuk mengakses dan menggunakan Situs dan Layanan untuk tujuan yang sah menurut hukum. Catatan yang kami miliki terkait dengan penggunaan Anda terhadap Layanan kepada Anda.</p>
            <p class="mb-4">Agar Layanan berfungsi secara efektif, Anda juga harus tetap memperbarui Informasi Akun Anda. Jika Anda tidak melakukannya ini, keakuratan dan keefektifan Layanan dapat dipengaruhi dan mungkin bahwa Anda adalah pemilik sah, dan bahwa Anda berwenang untuk memberikan kepada kami, semua Informasi Pendaftaran dan Akun dan informasi lain yang diperlukan untuk memfasilitasi penggunaan Layanan oleh Anda.</p>
            <p class="mb-4">Akses dan penggunaan Anda terhadap Layanan dapat terganggu dari waktu ke waktu karena salah satu dari beberapa alasan, termasuk, tanpa batasan, kerusakan peralatan, pemeliharaan, atau pembaruan rutin yang dilakukan KONTAKAMI, atau sebab lain di luar kontrol KONTAKAMI, atas kebijaksanaannya sendiri, dapat memilih untuk menghentikan, atau menghentikan Layanan. Dalam hal apa pun KONTAKAMI tidak akan bertanggung jawab kepada pihak mana pun atas kehilangan, biaya, atau kerusakan yang diakibatkan dari downtime terjadwal atau tidak terjadwal.</p>
            <p class="mb-4">Dari waktu ke waktu, KONTAKAMI dapat menyertakan fitur prio-prilis yang baru dan/atau diperbarui dan penggunaan uji coba (fitur "Pratinjau") dalam Layanan untuk pengguna Anda dan Anda mungkin diminta untuk memberikan Masukan Pratinjau apa pun. Selain itu, jika Anda memutuskan untuk menggunakan fitur Pratinjau, Anda setuju untuk mematuhi aturan atau batasan apa pun yang mungkin dilakukan oleh KONTAKAMI.</p>
            <p class="mb-4">Anda memahami bahwa begitu Anda menggunakan fitur Pratinjau, Anda mungkin tidak dapat kembali ke versi sebelumnya dari fitur yang sama atau serupa. Selain itu, jika pengembalian seperti itu dimungkinkan, Anda mungkin tidak dapat mengembalikan atau mengembalikan data yang dibuat dalam fitur Pratinjau kembali ke versi sebelumnya. Fitur Pratinjau disediakan berdasarkan "sebagaimana adanya" dan mungkin mengandung kesalahan atau ketidaktepatan yang dapat menyebabkan hilangnya data, korupsi atau kehilangan data dan/atau informasi dari perangkat yang terhubung. Anda mengakui dan setuju bahwa semua penggunaan fitur Pratinjau adalah risiko Anda sendiri.</p>
            <p class="mb-4">Layanan diberikan dengan dasar "sebagaimana adanya" dan "sebagaimana tersedia", dan penggunaan Layanan oleh Anda adalah risiko tunggal dan sendiri. Kami akan berusaha untuk memberitahukan (pada jam kerja normal) seputar permasalahan teknis yang mungkin dihadapi dengan penggunaan Layanan.</p>
            <p class="mb-4">Kami tidak menjamin bahwa: (a) Layanan akan memenuhi kebutuhan khusus Anda; (b) Layanan akan tidak terganggu, cepat, aman, atau bebas dari kekeliruan; (c) Layanan akan akurat dan dapat diandalkan; (d) kualitas dari segala produk, layanan, informasi, atau material lainnya yang dibeli atau diperoleh oleh Anda melalui Layanan akan memenuhi ekspektasi Anda; atau (e) segala kekeliruan dalam Layanan akan diperbaiki.</p>
            <p class="mb-4">Anda mengakui bahwa KONTAKAMI dapat menggabungkan pengguna pihak ketiga untuk menyediakan perangkat keras, perangkat lunak, jaringan, penyimpanan, dan teknologi lain untuk dapat menyediakan Layanan. Tindakan dan kelalaian pemasok pihak ketiga tersebut mungkin berada di luar kendali KONTAKAMI, dan KONTAKAMI tidak menerima tanggung jawab atas kerugian atau kerusakan yang diderita sebagai akibat dari tindakan dan kelalaian pihak ketiga tersebut. Atas nama diri sendiri dan pihak ketiga manapun tersebut, KONTAKAMI mengecualikan segala jaminan lain yang mungkin tersirat ataupun berlaku berdasarkan peraturan atau undang-undang lain yang berlaku, sepanjang diperkenankan berdasarkan hukum.</p>
            <p class="mb-4">Untuk kemudahan Anda, KONTAKAMI dapat mencantumkan tautan ke situs atau konten lain dalam Internet yang dimiliki atau dioperasikan oleh pihak ketiga. Situs atau konten yang ditautkan tersebut berada di bawah kendali Kami dan KONTAKAMI tidak bertanggung jawab untuk segala kekeliruan, kelalaian, keterlambatan, penghinaan, fitnah, kebohongan, pornografi, konten asusila, pelanggaran, atau material lain yang timbul dalam komunikasi atau konsekuensi dari situs-situs tersebut. Penggunaan situs pihak ketiga sepenuhnya menjadi risiko Anda sendiri. Anda mengakui dan sepakat bahwa, atas informasi yang terdapat dalam situs yang bertautan dengan dan dari Situs. Mengingat bahwa website pihak ketiga mungkin memiliki kebijakan privasi dan/atau standar keamanan berbeda yang berlaku dalam website mereka, kami menganjurkan Anda untuk menelaah kebijakan privasi dan syarat dan ketentuan situs-situs tersebut sebelum memberikan informasi pribadi apapun.</p>
            <p class="mb-4">Harap diketahui bahwa segala tautan ke situs atau konten lain manapun bukan merupakan bentuk dukungan atau verifikasi atas situs atau konten tersebut dan Anda setuju bahwa segala risiko dari akses terhadap situs atau konten yang ditautkan tersebut sepenuhnya ada pada pihak Anda.</p>
            <p class="mb-4">KONTAKAMI tidak akan memonitor segala hal terkait dengan pelanggan yang terkait dengan kepentingan penegakan hukum untuk kepentingan terorisme, penipuan, SARA, pornografi maupun kesusilaan, baik yang dilakukan secara sadar maupun tanpa disengaja, pelanggan saat ini ini memberitahukan hal penuh kepada KONTAKAMI untuk melakukan tindakan, baik berupa penonaktifan akun maupun melaporkannya kepada pihak berwenang.</p>

            <p class="font-bold mb-4 underline">Hak Kekayaan Intelektual KONTAKAMI</p>
            <p class="mb-4">Anda mengakui bahwa seluruh informasi dan data, seperti halaman situs, layanan situs, file data, teks, program komputer, audio, gambar, foto, animasi atau material lainnya (secara bersama-sama "<span class="font-bold">Konten</span>") yang dapat Anda akses sebagai bagian dari, atau melalui penggunaan Anda atas, Layanan serta Layanan itu sendiri adalah sepenuhnya milik KONTAKAMI. Anda mengakui dan menyetujui bahwa KONTAKAMI memiliki seluruh hak, kepemilikan dan kepentingan yang sah secara hukum di dalam dan pada Layanan dan Konten, termasuk setiap hak kekayaan intelektual yang ada dalam Layanan dan Konten (baik hak tersebut terdaftar atau tidak, dan di negara manapun dimana hak-hak tersebut timbul). Anda sepakat untuk tidak menuntut atau melakukan hal apapun yang tidak konsisten dengan kepemilikan tersebut.</p>
            <p class="mb-4">Anda memberikan KONTAKAMI, anak perusahaan, afiliasi, dan penerus hak KONTAKAMI suatu hak yang bebas royalti, tidak dapat dibatalkan, dan berlaku terus menerus (termasuk untuk keperluan komersial) untuk menggunakan informasi dan/atau data yang diperoleh KONTAKAMI melalui penggunaan Layanan oleh Anda, dengan ketentuan bahwa kami akan mengagregasi atau melakukan anonimisasi informasi atau data tersebut sebelum menggunakannya.</p>
            <p class="mb-4">Selain itu, Anda juga memberikan KONTAKAMI, anak perusahaan, afiliasi, dan penerus hak KONTAKAMI suatu hak yang berlaku di seluruh dunia, non-eksklusif, bebas royalti, tetap berlaku penuh, dapat dialihkan, dan dapat dipublikasikan untuk menggunakan, mereproduksi, mengubah, mengadaptasi, mengumumkan, membuat karya turunan dari, mendistribusikan, menampilkan di muka umum, dan mengumumkan di muka umum konten anda di seluruh dunia dalam media apapun untuk menyediakan dan mempromosikan Layanan, sepanjang diperkenankan peraturan perundang-undangan.</p>
            <p class="mb-4">Selain dari itu tersebut, KONTAKAMI tidak mengklaim hak kekayaan intelektual sehubungan dengan informasi dan konten yang Anda masukkan ke dalam layanan. Anda mengakui dan sepakat bahwa Hak penggunaan yang diberikan kepada Anda oleh Ketentuan Penggunaan ini bukanlah suatu pengalihan atau penjualan hak kepemilikan KONTAKAMI atas layanan dan konten, sehingga Anda tidak akan menggunakan Layanan dengan cara yang melanggar hak kepemilikan KONTAKAMI. Anda mengakui dan sepakat bahwa upaya apapun untuk menggunakan Layanan di luar yang diperbolehkan oleh lisensi ini akan mengakibatkan penarikan hak Anda sehubungan dengan Layanan dan dengan ini memberikan hak kepada KONTAKAMI untuk memproses pelanggaran tersebut berdasarkan peraturan perundang-undangan yang berlaku.</p>
            <p class="mb-4">Anda tidak boleh menggunakan nama dagang, nama dagang merek, logo atau nama domain terkait KONTAKAMI atau pihak ketiga tanpa izin dari pemilik terkait, kecuali dengan persetujuan tertulis sebelumnya dari KONTAKAMI. Anda dapat memberikan komentar, tanggapan, atau saran kepada kami sehubungan dengan Layanan dan kami bebas untuk menggunakannya tanpa kewajiban kepada Anda.</p>

            <p class="font-bold mb-4 underline">Keterbatasan Kewajiban & Ganti Rugi</p>
            <p class="mb-4">Anda mengakui dan sepakat bahwa sejauh mana diperbolehkan oleh hukum yang berlaku, KONTAKAMI tidak akan bertanggung jawab atas segala kerusakan dan/atau kerugian langsung, tidak langsung, insidental, khusus, konsekuensial, atau tipikal (exemplary damages) yang mungkin ditimbulkan akibat dari Layanan, termasuk kerugian yang berhubungan dengan hilangnya data, goodwill, reputasi, atau keuntungan. KONTAKAMI tidak akan memberikan ganti rugi atau mengembalikan biaya Layanan dalam keadaan apapun.</p>
            <p class="mb-4">KONTAKAMI tidak akan bertanggung jawab atas segala kerugian yang disebabkan oleh ketidaktepatan data atau penggunaan yang tidak sesuai dengan Ketentuan Penggunaan. Anda mengakui bahwa KONTAKAMI berhak untuk menunda atau menghentikan akun jika didapati penggunaan layanan yang mencurigakan atau melanggar peraturan. Segala kerugian yang timbul akibat hal ini adalah tanggung jawab Anda.</p>
            <p class="mb-4">Pada kasus apapun, KONTAKAMI dan para pemberi lisensinya, serta para penyedia layanan pihak ketiga, tidak akan bertanggung jawab lebih dari jumlah yang Anda bayarkan untuk Layanan atau yang sepadan dengan proporsi penggunaan Anda atas Layanan. Anda setuju untuk membebaskan KONTAKAMI dari segala klaim atau tuntutan yang timbul sebagai akibat dari pelanggaran Anda atas Ketentuan ini atau hukum yang berlaku.</p>

            <p class="font-bold mb-4 underline">Hukum dan Forum yang Mengatur Perselisihan</p>
            <p class="mb-4">Anda sepakat bahwa: (a) Layanan akan diberikan dari Indonesia; (b) Hukum Indonesia berlaku untuk Ketentuan Penggunaan ini, termasuk setiap permasalahan kontraktual atau non-kontraktual; (c) Setiap sengketa akan diselesaikan di Pengadilan Jakarta Selatan. Segala tuntutan hukum yang terkait dengan Layanan harus diajukan dalam waktu yang ditentukan oleh peraturan yang berlaku di Indonesia.</p>
            <p class="mb-4">KONTAKAMI dapat memilih untuk melanjutkan sengketa melalui mediasi atau arbitrase, yang harus disepakati oleh kedua belah pihak.</p>
            <p>SETIAP SENGKETA ATAU KLAIM YANG BERKAITAN DENGAN CARA APA PUN UNTUK LAYANAN ATAU KETENTUAN PENGGUNAAN INI AKAN DIAJUKAN DENGAN MENGIKUTI KETENTUAN DAN YURISDIKSI DARI PENGADILAN JAKARTA SELATAN.</p>
        </div>
    </div>
@endsection()
