-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIvs5PDolGDFfqRVHQPSVsJ/LaBqLt9hnJjbDyqW0Qk2gCgYIKoZIzj0DAQehRANCAAR3FKmZiL5/TrHSHbP/d1pHqYTVpp9Ia/t8fthHfiLLw2Nv1XmDtJRSbVWhu1Q2jvT+JflaR7cuTJBPZ3Q4QagK
-----END PRIVATE KEY-----